version: '3.8'

services:
  # Main PostgreSQL database for the application
  klinika_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Separate PostgreSQL database for running tests
  test_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_product_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # Django web application
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - klinika_db
    environment:
      - DATABASE_URL=postgres://your_db_user:your_db_password@product_db:5432/product_db
      - TELEGRAM_BOT_TOKEN=your-telegram-token

  # Telegram bot service
  bot:
    build: .
    command: python manage.py runbot
    volumes:
      - .:/app
    depends_on:
      - klinika_db
    environment:
      - DATABASE_URL=postgres://your_db_user:your_db_password@klinika_db:5432/product_db
      - TELEGRAM_BOT_TOKEN=your-telegram-token

  # Test runner service for Django tests
  test:
    build: .
    command: bash -c "pytest --disable-warnings"
    volumes:
      - .:/app
    depends_on:
      - test_db
    environment:
      - DATABASE_URL=postgres://test_user:test_password@test_db:5432/test_product_db
      - DJANGO_SETTINGS_MODULE=product_bot.settings_test

volumes:
  postgres_data:
  test_postgres_data:
